import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="w-screen h-screen flex items-center justify-center">
      <div className=" w-11/12 h-full flex justify-center items-center">
        <div className=" w-3/5 h-full flex items-center">
          <img src="/image.jpg" alt="Image" className=" w-full" />
        </div>
        <div className=" w-2/5 h-full flex items-center justify-center ">
          {children}
        </div>
      </div>
    </div>
  );
}
